---

- name: H4ckademy | Install dependencies
  sudo: true
  apt: name={{ item }} update_cache=yes
  with_items:
    - git

- name: H4ckademy | Install golang dependencies
  sudo: false
  environment:
    GOPATH: "/home/vagrant/go"
  command: /usr/local/go/bin/go get "{{ item }}"
  with_items:
    - github.com/gin-gonic/gin
    - github.com/gorilla/websocket
    - github.com/codegangsta/gin
