---
- name: H4ckademy workshop
  hosts: all
  remote_user: vagrant
  sudo: yes

  vars:
    - h4ckademy_path: "/home/vagrant/hack"

  roles:
    - debops.nodejs
    - Stouts.redis
    - golang
    - h4ckademy
